version: '3.8'

services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: radiantgo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - radiantgo-network

  mongodb:
    image: mongo:7
    container_name: radiantgo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: radiantgo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - radiantgo-network

volumes:
  redis_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  radiantgo-network:
    driver: bridge